### ISSUE TITLE
Support for pluggy 1.0?

### ISSUE THREAD

**Issue by mison6** [conda-forge/sqlfluff-feedstock#25]
### Comment:

Hello, is there anything in pluggy 1.0.0 that breaks in the latest release of sqlfluff? https://pluggy.readthedocs.io/en/stable/changelog.html#pluggy-1-0-0-2021-08-25. I couldn't see any issue, nor find anything reported online.

It would be great to be able to use sqlfluff and airflow in the same environment by allowing pluggy 1.0.0 in the recipe.

**Comment by thewchan** [comment]
Thanks for raising this; I'll see if I can lift that dependency pin in the conda recipe.
